import os
content = '<?xml version="1.0" encoding="utf-8"?>' + chr(10)
content += '<widget id="com.zhongyi.zhiban" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">' + chr(10)
content += '    <name>\u4e2d\u533b\u667a\u4f34</name>' + chr(10)
content += '    <description>\u4e2d\u533b\u667a\u4f34 - \u4e2d\u533b\u6cbb\u7597\u65b9\u6848\u67e5\u8be2\u4e0e\u5206\u4eab\u5e73\u53f0</description>' + chr(10)
content += '    <author email="dev@zhongyizhiban.app" href="https://zhongyizhiban.app">\u4e2d\u533b\u667a\u4f34\u56e2\u961f</author>' + chr(10)
content += '    <content src="index.html" />' + chr(10)
content += '    <allow-intent href="http://*/*" />' + chr(10)
content += '    <allow-intent href="https://*/*" />' + chr(10)
content += '    <access origin="http://192.168.11.138:*" />' + chr(10)
content += '    <access origin="http://*" />' + chr(10)
content += '    <preference name="Orientation" value="portrait" />' + chr(10)
content += '    <preference name="SplashScreenDelay" value="0" />' + chr(10)
content += '    <preference name="FadeSplashScreen" value="false" />' + chr(10)
content += '    <preference name="ShowSplashScreen" value="false" />' + chr(10)
content += '</widget>' + chr(10)

with open('android-app/config.xml', 'w', encoding='utf-8') as f:
    f.write(content)
print('config.xml updated')
